[2025-03-29T08:38:59.050+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_arsenalfc.extract __airflow_temporary_run_2025-03-28T21:35:57.648476+00:00__ [queued]>
[2025-03-29T08:38:59.061+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_arsenalfc.extract __airflow_temporary_run_2025-03-28T21:35:57.648476+00:00__ [queued]>
[2025-03-29T08:38:59.061+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2025-03-29T08:38:59.089+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): extract> on 2025-03-28 21:35:57.648417+00:00
[2025-03-29T08:38:59.097+0000] {standard_task_runner.py:60} INFO - Started process 188 to run task
[2025-03-29T08:38:59.100+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_arsenalfc', 'extract', '__***_temporary_run_2025-03-28T21:35:57.648476+00:00__', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/ArsenalDag.py', '--cfg-path', '/tmp/tmp72vf7mig']
[2025-03-29T08:38:59.103+0000] {standard_task_runner.py:88} INFO - Job 276: Subtask extract
[2025-03-29T08:38:59.118+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-29T08:38:59.159+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_arsenalfc.extract __airflow_temporary_run_2025-03-28T21:35:57.648476+00:00__ [running]> on host 0885a72a0a09
[2025-03-29T08:38:59.267+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_arsenalfc' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T21:35:57.648417+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='__***_temporary_run_2025-03-28T21:35:57.648476+00:00__'
[2025-03-29T08:38:59.268+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-29T08:38:59.269+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --jars /Drivers/SQL_Sever/jdbc/postgresql-42.7.3.jar /opt/***/spark/app/extract.py']
[2025-03-29T08:38:59.293+0000] {subprocess.py:86} INFO - Output:
[2025-03-29T08:38:59.299+0000] {subprocess.py:93} INFO - /home/***/.local/bin/spark-submit: line 27: /usr/local/lib/python3.8/site-packages/pyspark/bin/spark-class: No such file or directory
[2025-03-29T08:38:59.300+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-03-29T08:38:59.311+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-03-29T08:38:59.315+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=etl_arsenalfc, task_id=extract, execution_date=20250328T213557, start_date=20250329T083859, end_date=20250329T083859
[2025-03-29T08:38:59.329+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 276 for task extract (Bash command failed. The command returned a non-zero exit code 127.; 188)
[2025-03-29T08:38:59.354+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-29T08:38:59.384+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
