[2025-03-28T20:56:52.134+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_arsenalfc.extract scheduled__2024-06-21T00:00:00+00:00 [queued]>
[2025-03-28T20:56:52.154+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_arsenalfc.extract scheduled__2024-06-21T00:00:00+00:00 [queued]>
[2025-03-28T20:56:52.155+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-28T20:56:52.341+0000] {taskinstance.py:2217} INFO - Executing <Task(SparkSubmitOperator): extract> on 2024-06-21 00:00:00+00:00
[2025-03-28T20:56:52.358+0000] {standard_task_runner.py:60} INFO - Started process 4598 to run task
[2025-03-28T20:56:52.369+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_arsenalfc', 'extract', 'scheduled__2024-06-21T00:00:00+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/ArsenalDag.py', '--cfg-path', '/tmp/tmpw4ywhyhh']
[2025-03-28T20:56:52.374+0000] {standard_task_runner.py:88} INFO - Job 198: Subtask extract
[2025-03-28T20:56:52.405+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-28T20:56:52.494+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_arsenalfc.extract scheduled__2024-06-21T00:00:00+00:00 [running]> on host d87fcbd51e2e
[2025-03-28T20:56:52.722+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_arsenalfc' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-06-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-21T00:00:00+00:00'
[2025-03-28T20:56:52.745+0000] {base.py:83} INFO - Using connection ID 'spark_conn' for task execution.
[2025-03-28T20:56:52.747+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark:7077 --jars /Drivers/SQL_Sever/jdbc/postgresql-42.7.3.jar --name arrow-spark /opt/spark/app/Extract.py
[2025-03-28T20:56:52.916+0000] {spark_submit.py:488} INFO - /home/***/.local/lib/python3.8/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-03-28T20:56:58.073+0000] {spark_submit.py:488} INFO - 25/03/28 20:56:58 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-28T20:56:58.532+0000] {spark_submit.py:488} INFO - python3: can't open file '/opt/spark/app/Extract.py': [Errno 2] No such file or directory
[2025-03-28T20:56:58.542+0000] {spark_submit.py:488} INFO - 25/03/28 20:56:58 INFO ShutdownHookManager: Shutdown hook called
[2025-03-28T20:56:58.543+0000] {spark_submit.py:488} INFO - 25/03/28 20:56:58 INFO ShutdownHookManager: Deleting directory /tmp/spark-434dff06-4fc3-4741-b8a6-f401b28274ab
[2025-03-28T20:56:58.593+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark:7077 --jars /Drivers/SQL_Sever/jdbc/postgresql-42.7.3.jar --name arrow-spark /opt/spark/app/Extract.py. Error code is: 2.
[2025-03-28T20:56:58.595+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_arsenalfc, task_id=extract, execution_date=20240621T000000, start_date=20250328T205652, end_date=20250328T205658
[2025-03-28T20:56:58.604+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 198 for task extract (Cannot execute: spark-submit --master spark:7077 --jars /Drivers/SQL_Sever/jdbc/postgresql-42.7.3.jar --name arrow-spark /opt/spark/app/Extract.py. Error code is: 2.; 4598)
[2025-03-28T20:56:58.651+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-28T20:56:58.665+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
