[2025-03-28T20:51:28.377+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_arsenalfc.extract scheduled__2024-05-27T00:00:00+00:00 [queued]>
[2025-03-28T20:51:28.397+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_arsenalfc.extract scheduled__2024-05-27T00:00:00+00:00 [queued]>
[2025-03-28T20:51:28.398+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2025-03-28T20:51:28.432+0000] {taskinstance.py:2217} INFO - Executing <Task(SparkSubmitOperator): extract> on 2024-05-27 00:00:00+00:00
[2025-03-28T20:51:28.447+0000] {standard_task_runner.py:60} INFO - Started process 1334 to run task
[2025-03-28T20:51:28.460+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_arsenalfc', 'extract', 'scheduled__2024-05-27T00:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/ArsenalDag.py', '--cfg-path', '/tmp/tmpxibi9plx']
[2025-03-28T20:51:28.468+0000] {standard_task_runner.py:88} INFO - Job 161: Subtask extract
[2025-03-28T20:51:28.503+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-28T20:51:28.587+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_arsenalfc.extract scheduled__2024-05-27T00:00:00+00:00 [running]> on host d87fcbd51e2e
[2025-03-28T20:51:28.791+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_arsenalfc' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-05-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-27T00:00:00+00:00'
[2025-03-28T20:51:28.818+0000] {base.py:83} INFO - Using connection ID 'spark_conn' for task execution.
[2025-03-28T20:51:28.820+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark:7077 --jars /Drivers/SQL_Sever/jdbc/postgresql-42.7.3.jar --name arrow-spark /opt/spark/app/Extract.py
[2025-03-28T20:51:28.950+0000] {spark_submit.py:488} INFO - /home/***/.local/lib/python3.8/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-03-28T20:51:35.153+0000] {spark_submit.py:488} INFO - 25/03/28 20:51:35 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-28T20:51:35.892+0000] {spark_submit.py:488} INFO - python3: can't open file '/opt/spark/app/Extract.py': [Errno 2] No such file or directory
[2025-03-28T20:51:35.919+0000] {spark_submit.py:488} INFO - 25/03/28 20:51:35 INFO ShutdownHookManager: Shutdown hook called
[2025-03-28T20:51:35.926+0000] {spark_submit.py:488} INFO - 25/03/28 20:51:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-a93ea6af-8c8d-4a2f-95dd-8fe02d8bc2e5
[2025-03-28T20:51:36.162+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark:7077 --jars /Drivers/SQL_Sever/jdbc/postgresql-42.7.3.jar --name arrow-spark /opt/spark/app/Extract.py. Error code is: 2.
[2025-03-28T20:51:36.167+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=etl_arsenalfc, task_id=extract, execution_date=20240527T000000, start_date=20250328T205128, end_date=20250328T205136
[2025-03-28T20:51:36.201+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 161 for task extract (Cannot execute: spark-submit --master spark:7077 --jars /Drivers/SQL_Sever/jdbc/postgresql-42.7.3.jar --name arrow-spark /opt/spark/app/Extract.py. Error code is: 2.; 1334)
[2025-03-28T20:51:36.245+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-28T20:51:36.284+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
